export const All_languages = [
     { value: "en_US", name: "English US (en_US)" },
     { value: "en", name: "English (en)" },
     { value: "af", name: "Afrikaans" },
     { value: "sq", name: "Albanian" },
     { value: "ar", name: "Arabic" },
     { value: "az", name: "Azerbaijani" },
     { value: "bn", name: "Bengali" },
     { value: "bg", name: "Bulgarian" },
     { value: "ca", name: "Catalan" },
     { value: "zh_CN", name: "Chinese (CHN)" },
     { value: "zh_HK", name: "Chinese (HKG)" },
     { value: "zh_TW", name: "Chinese (TAI)" },
     { value: "hr", name: "Croatian" },
     { value: "cs", name: "Czech" },
     { value: "da", name: "Danish" },
     { value: "nl", name: "Dutch" },
     { value: "en_GB", name: "English (UK)" },
     { value: "et", name: "Estonian" },
     { value: "fil", name: "Filipino" },
     { value: "fi", name: "Finnish" },
     { value: "fr", name: "French" },
     { value: "de", name: "German" },
     { value: "el", name: "Greek" },
     { value: "gu", name: "Gujarati" },
     { value: "ha", name: "Hausa" },
     { value: "he", name: "Hebrew" },
     { value: "hi", name: "Hindi" },
     { value: "hu", name: "Hungarian" },
     { value: "id", name: "Indonesian" },
     { value: "ga", name: "Irish" },
     { value: "it", name: "Italian" },
     { value: "ja", name: "Japanese" },
     { value: "kn", name: "Kannada" },
     { value: "kk", name: "Kazakh" },
     { value: "ko", name: "Korean" },
     { value: "lo", name: "Lao" },
     { value: "lv", name: "Latvian" },
     { value: "lt", name: "Lithuanian" },
     { value: "mk", name: "Macedonian" },
     { value: "ms", name: "Malay" },
     { value: "ml", name: "Malayalam" },
     { value: "mr", name: "Marathi" },
     { value: "nb", name: "Norwegian" },
     { value: "fa", name: "Persian" },
     { value: "pl", name: "Polish" },
     { value: "pt_BR", name: "Portuguese (BR)" },
     { value: "pt_PT", name: "Portuguese (POR)" },
     { value: "pa", name: "Punjabi" },
     { value: "ro", name: "Romanian" },
     { value: "ru", name: "Russian" },
     { value: "sr", name: "Serbian" },
     { value: "sk", name: "Slovak" },
     { value: "sl", name: "Slovenian" },
     { value: "es", name: "Spanish" },
     { value: "es_AR", name: "Spanish (ARG)" },
     { value: "es_ES", name: "Spanish (SPA)" },
     { value: "es_MX", name: "Spanish (MEX)" },
     { value: "sw", name: "Swahili" },
     { value: "sv", name: "Swedish" },
     { value: "ta", name: "Tamil" },
     { value: "te", name: "Telugu" },
     { value: "th", name: "Thai" },
     { value: "tr", name: "Turkish" },
     { value: "uk", name: "Ukrainian" },
     { value: "ur", name: "Urdu" },
     { value: "uz", name: "Uzbek" },
     { value: "vi", name: "Vietnamese" },
     { value: "zu", name: "Zulu" },
];